name: Test
on: [push]
jobs:
  on_build_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
      - name: Run Tests
        run: python -m unittest ISSL/test.py

